CREATE TABLE POST
(ID BIGINT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(400) NOT NULL,
CONTENT VARCHAR(2000) NULL,
CREATED TIMESTAMP
);

CREATE TABLE COMMENT
(ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 POST_ID BIGINT NOT NULL,
 CONTENT VARCHAR(2000) NULL,
 CREATED TIMESTAMP
);

CREATE TABLE EMPLOYEE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    SURNAME VARCHAR(100),
    SPECIAL VARCHAR(100)
);

CREATE TABLE WORKER(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    EMPLOYEE_ID BIGINT NULL,
    SPECIAL VARCHAR(100)
);

ALTER TABLE COMMENT
    ADD CONSTRAINT COMMENT_POSTID
    FOREIGN KEY (POST_ID) REFERENCES POST(ID);

ALTER TABLE WORKER
    ADD CONSTRAINT WORKER_EMPLOYEE_ID
        FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID);

