CREATE TABLE POST
(ID BIGINT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(400) NOT NULL,
CONTENT VARCHAR(2000) NULL,
CREATED TIMESTAMP
);

CREATE TABLE COMMENT
(ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 POST_ID BIGINT NOT NULL,
 CONTENT VARCHAR(2000) NULL,
 CREATED TIMESTAMP
);

CREATE TABLE EMPLOYEE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    SURNAME VARCHAR(100),
    SPECIAL VARCHAR(100)
);

CREATE TABLE WORKER(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    EMPLOYEE_ID BIGINT NULL,
    SPECIAL VARCHAR(100)
);

CREATE TABLE vw_towar
(
    tw_id           bigint IDENTITY (1, 1) NOT NULL,
    tw_symbol       varchar(255),
    tw_nazwa        varchar(255),
    st_mag_id       bigint,
    st_stan         float(53),
    tc_cena_brutto1 float(53),
    CONSTRAINT pk_vwtowar PRIMARY KEY (tw_id)
)
    GO

ALTER TABLE COMMENT
    ADD CONSTRAINT COMMENT_POSTID
    FOREIGN KEY (POST_ID) REFERENCES POST(ID);

ALTER TABLE WORKER
    ADD CONSTRAINT WORKER_EMPLOYEE_ID
        FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID);

